const DIGIT_PRESSED = "DIGIT_PRESSED";
const EVAL_PRESSED = "EVAL_PRESSED";
const CLEAR_PRESSED = "CLEAR_PRESSED";
const DECIMAL_PRESSED = "DECIMAL_PRESSED";
const MATH_OPERATION_PRESSED = "MATH_OPERATION_PRESSED";

export const actions = {
  DIGIT_PRESSED,
  EVAL_PRESSED,
  CLEAR_PRESSED,
  DECIMAL_PRESSED,
  MATH_OPERATION_PRESSED
};
